### ISSUE TITLE
Delete followed by create of entity with same UUID fails

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#455] opened 2020-07-16 18:35 UTC
1. Delete an entity with a given UUID
2. Try to re-create the entity in the same provider with the same UUID (using `client.create_with_meta()` to set the UUID)
3. Papiea fails with a Mongo error:

```
papiea_1   | Default handle got error: Cannot create entity Error, MongoError: E11000 duplicate key error collection: papiea.entity index: provider_specific_entity_uuid dup key: { metadata.uuid: "d63afab6-9903-47f1-8007-801a8b340fd7", metadata.provider_prefix: "bmaas" }
papiea_1   | error       2020-07-16T18:32:59.438Z Error msg: Cannot create entity Error, MongoError: E11000 duplicate key error collection: papiea.entity index: provider_specific_entity_uuid dup key: { metadata.uuid: "d63afab6-9903-47f1-8007-801a8b340fd7", metadata.provider_prefix: "bmaas" }. Details: ; 
papiea_1   |                 Cause: message - Error: Cannot create entity Error, MongoError: E11000 duplicate key error collection: papiea.entity index: provider_specific_entity_uuid dup key: { metadata.uuid: "d63afab6-9903-47f1-8007-801a8b340fd7", metadata.provider_prefix: "bmaas" }
papiea_1   | audit       2020-07-16T18:32:59.438Z -- {
papiea_1   |   headers: {
papiea_1   |     'content-length': '163',
papiea_1   |     'content-type': 'application/json;charset=utf-8',
papiea_1   |     'user-agent': 'axios/0.18.1',
papiea_1   |     accept: 'application/json, text/plain, */*',
papiea_1   |     authorization: 'Bearer IAmTheAdmin',
papiea_1   |     connection: 'close',
papiea_1   |     host: 'localhost:3333'
papiea_1   |   },
papiea_1   |   method: 'POST',
papiea_1   |   request_body: {
papiea_1   |     metadata: {
papiea_1   |       extension: { owner: 'gazebo' },
papiea_1   |       kind: 'machine-type',
papiea_1   |       provider_prefix: 'bmaas',
papiea_1   |       provider_version: '0.0.1',
papiea_1   |       spec_version: 0,
papiea_1   |       uuid: 'd63afab6-9903-47f1-8007-801a8b340fd7'
papiea_1   |     },
papiea_1   |     spec: { cores: 1, disks: [], mem_gib: 0.001, name: 'potato', nics: [] }
papiea_1   |   },
papiea_1   |   request_ip: '::ffff:192.168.32.1',
papiea_1   |   response_body: {
papiea_1   |     error: {
papiea_1   |       code: 500,
papiea_1   |       errors: [
papiea_1   |         {
papiea_1   |           message: 'Cannot create entity Error, MongoError: E11000 duplicate key error collection: papiea.entity index: provider_specific_entity_uuid dup key: { metadata.uuid: "d63afab6-9903-47f1-8007-801a8b340fd7", metadata.provider_prefix: "bmaas" }'
papiea_1   |         }
papiea_1   |       ],
papiea_1   |       message: 'Cannot create entity Error, MongoError: E11000 duplicate key error collection: papiea.entity index: provider_specific_entity_uuid dup key: { metadata.uuid: "d63afab6-9903-47f1-8007-801a8b340fd7", metadata.provider_prefix: "bmaas" }',
papiea_1   |       type: 'server_error'
papiea_1   |     }
papiea_1   |   },
papiea_1   |   status_code: 500,
papiea_1   |   url: '/services/bmaas/0.0.1/machine-type',
papiea_1   |   user: { is_admin: true }
papiea_1   | }
```

**Comment by Emulebest** [comment] 2020-07-17 08:03
This is not a bug in current state of things as the entities are not removed but instead marked as `deleted_at` and hidden from search results

**Comment by joshua-berry-ntnx** [comment] 2020-07-17 15:49
aha, fair enough. This might actually be desirable behavior then. We can probably leave this one for future discussion as it's not blocking anything right now.

**Comment by shlomi-nx** [comment] 2020-07-23 01:34
Potentially we can move the graveyard to a different collection that will allow for duplicate ids

**Comment by shlomi-nx** [comment] 2020-07-23 02:37
@Emulebest This just reached priority.. Please handle this today. Essentially, lets move deleted items to a new mongo-db collection for graveyard. That collection may have multiple items with the same id, so the primary key should be on id and delete date. Perhaps GET on deleted should not work, but filter should, and it may return more than a single item.

@joshua-berry-ntnx thoughts?

**Comment by joshua-berry-ntnx** [comment] 2020-07-23 03:37
I have a slight aesthetic preference for having a separate graveyard API, but I think filter with a special parameter is also fine.

One thing we need to think about: spec_version. We should probably ensure spec_version is somehow unique or different between previous and new versions of a particular entity. Otherwise you could wind up in pathological cases like this:

1. Client A fetches info on an entity, which has spec_version 1, then gets delayed, swapped out, decides to take a nap, etc.
2. Client B deletes the entity
3. Client C creates the entity again, which gets spec_version 1.
4. Client A wakes up and tries updating the entity with spec_version 1. The update succeeds, even though the entity has been deleted and recreated.

So I think we may want to consider persisting the spec_version even after the entity is gone, at least for a reasonable amount of time (and make deletion be a spec_version increment).

**Comment by Emulebest** [comment] 2020-07-23 10:42
> I have a slight aesthetic preference for having a separate graveyard API, but I think filter with a special parameter is also fine.
> 
> One thing we need to think about: spec_version. We should probably ensure spec_version is somehow unique or different between previous and new versions of a particular entity. Otherwise you could wind up in pathological cases like this:
> 
> 1. Client A fetches info on an entity, which has spec_version 1, then gets delayed, swapped out, decides to take a nap, etc.
> 2. Client B deletes the entity
> 3. Client C creates the entity again, which gets spec_version 1.
> 4. Client A wakes up and tries updating the entity with spec_version 1. The update succeeds, even though the entity has been deleted and recreated.
> 
> So I think we may want to consider persisting the spec_version even after the entity is gone, at least for a reasonable amount of time (and make deletion be a spec_version increment).

I'd have this as a separate ticket to be honest, because a quick solution would be to make spec_version range unique (take latest deleted entity spec version as X and forbid using spec_version 0-X). A better one will take some time to get around the rough edges and corner cases

**Closed** 2020-07-23 17:31 UTC
Labels: enhancement

**Comment by shlomi-nx** [comment] 2020-07-23 18:17
> I have a slight aesthetic preference for having a separate graveyard API, but I think filter with a special parameter is also fine.
> 
> One thing we need to think about: spec_version. We should probably ensure spec_version is somehow unique or different between previous and new versions of a particular entity. Otherwise you could wind up in pathological cases like this:
> 
> 1. Client A fetches info on an entity, which has spec_version 1, then gets delayed, swapped out, decides to take a nap, etc.
> 2. Client B deletes the entity
> 3. Client C creates the entity again, which gets spec_version 1.
> 4. Client A wakes up and tries updating the entity with spec_version 1. The update succeeds, even though the entity has been deleted and recreated.
> 
> So I think we may want to consider persisting the spec_version even after the entity is gone, at least for a reasonable amount of time (and make deletion be a spec_version increment).

That is a fantastic idea. I am not sure about making the deletion a spec_version increment, but when creating a new entity, search the graveyard and create the new entity with `max(graveyard.id.spec_version)+1`
