### ISSUE TITLE
status-only field can be set/update through spec update

### ISSUE THREAD

**Issue by yitingwnutanix** [nutanix/papiea#565] opened 2020-12-09 08:28 UTC
### System Details

- **Papiea Engine version**: 0.8.5_1748
- **Papiea SDK version:** 0.8.5
- **Papiea Client version:** 0.8.5

### Describe the Bug

I had an entity with status-only fields. When I created the entity with status-only field set in spec, Papiea didn't report any error. The status-only field doesn't have specs. Papiea should report error with such update request. 
When I remove the status-only filed from specs when creating the entity, Papiea report 400 error with error message: 
`{"error":{"code":400,"errors":[{"message":"[status-only field] is a required field"}],"message":"Validation failed.","type":"validation_error"}}` 

### Expected/Actual Behavior

Papiea should response with error when we tried to update the status-only field through spec update. 

### Steps to Reproduce

1. I had a kind defined as follow in bmaas/src/kinds: 
[test-kind.txt](https://github.com/nutanix/papiea/files/5664453/test-kind.txt)
2. I create the kind and register the kind_procedure in bmaas/src/main.ts
3. I ran BMaaS and created an entity through the kind_procedure. It succeeds. No errors are reported.  
4. I removed the status field from the specs when creating the entity, Papiea returned the error message:
`{"error":{"code":400,"errors":[{"message":"status is a required field"}],"message":"Validation failed.","type":"validation_error"}}`

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by shlomi-nx** [comment] 2020-12-09 18:52
@yitingwnutanix Until this is done, please remove the offending field from the `required` list as a workaround. Will this be sufficient?

**Comment by shlomi-nx** [comment] 2020-12-09 18:56
@nitesh-idnani1, is this related to https://github.com/nutanix/papiea/issues/514?

**Comment by nitesh-idnani1** [comment] 2020-12-09 20:01
> @nitesh-idnani1, is this related to #514?

No, doesn't look like it's related since this one deals with spec updates only. As I understand @yitingwnutanix, there are two issue fixes here i.e.
1) Throw error for status-only field update/insert through update spec function.
2) Overlook `required` constraint for status-only fields in case of spec updates

I'll first check the behavior for status-only fields within the spec updates in papiea, and update the issues that I find out.

**Comment by shlomi-nx** [comment] 2020-12-09 20:24
@nitesh-idnani1, thanks for the analysis. 

Notes on the points above - when creating an entity we need to validate based on the entity's constructor:
1. If the entity has a constructor, validate input ONLY based on the constructor input schema
2. If the entity has no custom constructor, validate only the (optional) `metadata` and `spec` portions of the schema, ignoring any fields do not related to them (for now these are only `status-only` fields)

**Comment by nitesh-idnani1** [comment] 2020-12-10 18:38
I had a discussion with @Ntnx-Igor-Korotach, and we decided on the following changes to resolve this issue

1. To throw a validation error while registering the provider if a status-only field is marked as required since that creates a invalid schema considering the definition of `status-only` fields.
2. To throw a validation error while create/update spec if it contains a status-only field.

@shlomi-nx @yitingwnutanix
Feel free to add your comments and let me know if we need to discuss something.

**Comment by yitingwnutanix** [comment] 2020-12-10 21:04
@nitesh-idnani1 
1. I don't understand why status-only filed can't be marked as required. I think being marked as "required" means that the field can't be undefined for in the entity's status. 
2. Looks good to me.

**Comment by shlomi-nx** [comment] 2020-12-10 21:14
@yitingwnutanix it's not that it status-only fields cannot be marked as required. It's just that we never intended for it, and it sort of happened as a bug, and then kept and patched. The problem is we don't have full semantics yet on what does this actually mean (outside of the "contract") and how it should be handled to give a consistent experience to users.

Let's disallow (or simply ignore with a warning on the provider sdk) any status-only mandatory marks until we have a clear understanding of what we need.

**Comment by nitesh-idnani1** [comment] 2020-12-10 21:32
> @yitingwnutanix it's not that it status-only fields cannot be marked as required. It's just that we never intended for it, and it sort of happened as a bug, and then kept and patched. The problem is we don't have full semantics yet on what does this actually mean (outside of the "contract") and how it should be handled to give a consistent experience to users.
> 
> Let's disallow (or simply ignore with a warning on the provider sdk) any status-only mandatory marks until we have a clear understanding of what we need.

I think we'll have to throw an exception for required status-only field in schema, otherwise this issue will reproduce every time there's a spec insert/update for the entity.

**Comment by yitingwnutanix** [comment] 2020-12-10 21:39
@shlomi-nx Thanks for the explanation.

**Closed** 2020-12-17 09:23 UTC
