### ISSUE TITLE
Python SDK: ctx.check_permission() throws KeyError on "Authorization" header

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#436] opened 2020-06-26 23:02 UTC
From the Papiea SDK (used in Griffon):
```
griffon_1  | Traceback (most recent call last):
griffon_1  |   File "/home/src/papiea/papiea-python-sdk/papiea/python_sdk.py", line 416, in procedure_callback_fn
griffon_1  |     result = await handler(
griffon_1  |   File "main.py", line 138, in image_node_handler
griffon_1  |     allowed = await ctx.check_permission([(Action.Update, entity.metadata)])
griffon_1  |   File "/home/src/papiea/papiea-python-sdk/papiea/python_sdk_context.py", line 54, in check_permission
griffon_1  |     headers["Authorization"] = self.headers["Authorization"]
griffon_1  | KeyError: 'Authorization'
```

This only seems to happen on a procedure call (there was an immediately-preceding POST which created an entity just fine, with the same authorization). It's not clear to me why it's happening, as the Papiea audit logs show an authorization header is being sent to Griffon:

```
papiea_1   | error       2020-06-26T22:52:40.155Z Error msg: Procedure invocation failed.. Details: ; 
papiea_1   |                 Cause: message - Error: undefined; 
papiea_1   |                 Cause: errors - Error: undefined; 
papiea_1   |                 Cause: stacktrace - Error: undefined
papiea_1   | audit       2020-06-26T22:52:40.156Z -- {
papiea_1   |   headers: {
papiea_1   |     'accept-encoding': 'gzip, deflate',
papiea_1   |     'content-length': '1882',
papiea_1   |     'content-type': 'application/json',
papiea_1   |     'user-agent': 'Python/3.8 aiohttp/3.6.2',
papiea_1   |     accept: '*/*',
papiea_1   |     authorization: 'Bearer <redacted>',
papiea_1   |     host: 'papiea:3000'
papiea_1   |   },
papiea_1   |   method: 'POST',
papiea_1   |   request_body: {
papiea_1   |     input: {
...
papiea_1   |     }
papiea_1   |   },
papiea_1   |   request_ip: '::ffff:192.168.16.4',
papiea_1   |   response_body: {
papiea_1   |     error: {
papiea_1   |       code: 500,
papiea_1   |       errors: [ {} ],
papiea_1   |       message: 'Procedure invocation failed.',
papiea_1   |       type: 'procedure_invocation_error'
papiea_1   |     }
papiea_1   |   },
papiea_1   |   status_code: 500,
papiea_1   |   url: '/services/griffon/0.1.0/node/9d81b8e3-6fb5-42db-b733-ffe2269ec9f2/procedure/image',
papiea_1   |   user: { is_admin: true }
papiea_1   | }
```

**Comment by joshua-berry-ntnx** [comment] 2020-06-26 23:06
Some more context from the Griffon code, here is the offending call to `check_permission()`:

```py
async def image_node_handler(ctx, entity, config):
  """
...
  """
  logger.debug(f"image_node: input config:\n%s" % config)
  allowed = await ctx.check_permission([(Action.Update, entity.metadata)])
```

**Comment by Emulebest** [comment] 2020-07-21 11:31
Checked both in `papiea-examples` repo and in `griffon` using `run_client` sample
getting
![image](https://user-images.githubusercontent.com/26462528/88050069-d8a0c280-cb5e-11ea-85c4-8e3085e65139.png)
Can you follow up with steps that you got you to this error in the first place?

**Comment by Emulebest** [comment] 2020-07-21 11:33
@joshua-berry-ntnx note there is a fix to a different problem found while debugging (full provider validation issue) #464

**Comment by joshua-berry-ntnx** [comment] 2020-07-21 17:57
Yes, let's retry with the newer SDK/engine and see. I can't think of a case where we should reach the failing code without having an authorization header present, yet that seems to be what happened before.

**Comment by Emulebest** [comment] 2020-07-22 07:48
I'm closing this as I couldn't reproduce, be sure to reopen if this happens again!

**Closed** 2020-07-22 07:48 UTC
Labels: backlog
